### ISSUE TITLE
Question about custom armor

### ISSUE THREAD

**Issue by uwni** [Patbox/polymer#10]
in the `eu.pb4.polymer.api.resourcepack.PolymerRPUtils#requestArmor(Identifier)` function, colors from (1, 1, 1) to (255, 255, 255) are used to register my custom armor with a vanilla dyed leather armor. but why only odd rgb number are used?

[wiki](https://minecraft.fandom.com/wiki/Dye#Dyeing_armor) said that there are 73.4% sRGB being used in the dyed leather armor. Could we use the rest 26.6% to register custom model? or use them first

**Comment by Patbox** [comment]
Because you can get any color with commands. It works just fine and doesn't cause issues from my testing anyway, but it would be trival to change that
