### ISSUE TITLE
maybe dont require fabric registry sync?

### ISSUE THREAD

**Issue by MCBEModder2020** [Patbox/polymer#102]
fabric registry sync causes an issue with a fabric client trying to join a fabric server of a different version via viaversion on the server. it is possible to patch it out of the fabric api jar by using:
```
jar -xf <fabric api jar> fabric.mod.json 
```
then edit the jars part of the file to not contain registry sync
then do
```
jar -uf <fabric api jar> fabric.mod.json 
```

**Comment by Patbox** [comment]
Polymer doesn't require it. Other mods migh, as aside of registry sync, that library adds some registry related events. This should be patched on ViaFabric side of things, as polymer doesn't want to break modpacks and such

**Comment by MCBEModder2020** [comment]
nvm i solved my issue by adding an `if (true) {continue;}` to smth in fabric api
