### ISSUE TITLE
Improve documentation on the fact you need to register ItemGroups via Polymer

### ISSUE THREAD

**Issue by msparkles** [Patbox/polymer#103]
It seems that the items registered on server work with recipe lookups, but not in the REI/EMI item index/entries. What's the status on adding compatibility for that? We very vaguely remember it used to work before...

**Comment by Patbox** [comment]
What version are you on? Items should work with REI/EMI still

**Comment by msparkles** [comment]
0.7.5 / 1.20.4

**Comment by msparkles** [comment]
*As in, the items don't appear in the item search

**Comment by Patbox** [comment]
Can't replicate
![2024-01-15_22 43 27](https://github.com/Patbox/polymer/assets/39821509/2c660dee-c579-44dc-9ad6-22de17df410c)

**Comment by Patbox** [comment]
And search also works 
![image](https://github.com/Patbox/polymer/assets/39821509/1c60cd9e-8d17-4db6-9e14-ad26605460e1)

**Comment by msparkles** [comment]
Is there extra setup to having it work other than installing polymer on the client?

**Comment by Patbox** [comment]
On client no, but you need to make sure server uses the same protocol version (so no old server + viaversion) and thst the mods have correctly setup polymer item group

**Comment by msparkles** [comment]
User error, didn't know this. Could this be better documented, then?

**Comment by msparkles** [comment]
Actually, how do you.. do that?
