### ISSUE TITLE
Polymer + ViaFabric 1.20.4 seems to not omit experimental mobs for Fabric 1.20.2 clients

### ISSUE THREAD

**Issue by Ampflower** [Patbox/polymer#109]
See: Modflower/Polysit#7 as initially reported by @ArkoSammy12

## Steps to Reproduce:
- On server:
  - Use Minecraft 1.20.4
  - Install Fabric API, ViaFabric, ViaRewind, Polymer, any Polymer-based mod (i.e. Polysit, Polyfactory)
    - It seems that any registry modification is required, as bare Polymer doesn't trip the bug.
- On client:
  - Use Minecraft 1.20.2
  - Install Fabric API; the vanilla client seems unaffected
- Start the server with the given mod set
- Join the server

## Expected results:
As a vanilla client would do; join perfectly fine

## Actual results:
Claims a conflict on the Minecraft namespace regarding the Breeze and Wind Charge.

## Other things of note:
The registries it conflicts on seems to always be the registry modified by mods
- Polysit only trips the entity registry
- Polyfactory trips the block registry

It seems that 1.20.1 clients get mangled entity data handlers

## Logs:
[From server](https://mclo.gs/unxnNgM) - not particularly helpful for more than versions

[From client](https://mclo.gs/5LbpBB0)

[ViaVersion dump](https://dump.viaversion.com/192aa3afd02a621ab569400d1c62c30f07963758c2f8c0a477999b3ac5d9b7b0)

**Comment by Patbox** [comment]
I imagine it doesn't fully cancel full logic, but to be fair it also is kinda issue on ViaVersion part for not canceling that packet entirely

**Comment by Ampflower** [comment]
Fair; was just about to duplicate this issue there in case it was more their end rather than yours.

**Comment by Kichura** [comment]
marked the external issue as "help wanted" cuz the via dev team refused to do anything with it, as for myself - i do encourage requesting for help on how to solve it.

**Comment by Kichura** [comment]
Fixed.
