### ISSUE TITLE
PolymerTexturedBlock onBreak override broken... I think.

### ISSUE THREAD

**Issue by JacobMunoz** [Patbox/polymer#113]
I'm finding a change in the textured block bindings... not sure what to try.  I've removed the block from my mod for the time being.

my custom textured block:
public class UrlPostBlock extends Block implements PolymerTexturedBlock {
....
}
has an onBreak event, that works in 1.20.1 and 1.20.2, but not 1.20.4.

 error: onBreak(World,BlockPos,BlockState,PlayerEntity) in UrlPostBlock cannot override onBreak(World,BlockPos,BlockState,PlayerEntity) in Block
    public void onBreak(World world, BlockPos pos, BlockState state, PlayerEntity player){
                ^
  return type void is not compatible with BlockState

any help would help.

Thanks much

**Comment by Patbox** [comment]
Thats a vanilla block method, so it's likely just update change
