### ISSUE TITLE
Compile for 1.20.5 snapshot 24w13a?

### ISSUE THREAD

**Issue by imeesa** [Patbox/polymer#114]
I would like to request that this library be compiled for Minecraft 24w13a.

**Comment by imeesa** [comment]
I am developing a content mod for this version, and need to use Polymer as some of the players use custom clients.

**Comment by Patbox** [comment]
The 1.20.5 (snapshot) port is unfinished, as I still want to make some breaking changes!

**Comment by imeesa** [comment]
Ah.
