### ISSUE TITLE
Custom hoe playing sound twice for the client breaking blocks

### ISSUE THREAD

**Issue by imeesa** [Patbox/polymer#116]
I have a simple custom hoe, simply `

    public WatermelonHoe(Settings settings) {
        super(WATERMELON_MATERIAL, -2, 0, settings);
    }

    @Override
    public Item getPolymerItem(ItemStack itemStack, ServerPlayerEntity player) {
        return Items.DIAMOND_HOE;
    }`.

When the client breaks blocks that would be instantly mined using this hoe (e.g. leaves, grass), the block breaking sound will play twice. Other clients will not hear this sound twice, only once.

**Comment by Patbox** [comment]
This will be fixed in 1.20.5
