### ISSUE TITLE
Autohost requires resource pack on vanilla client even when required is set to false in config

### ISSUE THREAD

**Issue by ItsNoGood** [Patbox/polymer#121]
I have (by default) 
"required": false in auto-host.json
"markResourcePackAsRequiredByDefault": false in resource-pack.json
require-resource-pack=false in server.properties

But when I joined my server I still got the popup screen saying the resource pack is required and the only 2 buttons being to use it or disconnect.

Am I missing something or is this a bug? I'm using Polyfactory as well, does Polyfactory override the settings and just force itself to be required or something?

**Comment by Patbox** [comment]
Mods can override the requirement yes. This is the case here.
