### ISSUE TITLE
Texture for item not working

### ISSUE THREAD

**Issue by minigamerking** [Patbox/polymer#123]
This could just be me being stupid and not realizing a really simple mistake but in my [mod](https://github.com/minigamerking/polyweapons-1.20.1) the texture for the lifesteal sword is still just a diamond sword and its texture isn't overwritten. Once again it could just be me and not the library but I thought to ask the library since it could be something im doing wrong.
![image_2024-05-22_204852461](https://github.com/Patbox/polymer/assets/136130810/2de8d5b4-e773-48c8-abd8-03b81b54d0ae)
![Screenshot 2024-05-22 204838](https://github.com/Patbox/polymer/assets/136130810/60b627a4-32d5-4c5e-a7eb-11a2c8f1019a)

**Comment by minigamerking** [comment]
Does anyone know why this is happening?

**Comment by JongWasTaken** [comment]
Just to make sure: you ran `/polymer generate-pack` right?  
I fee like thats the easiest way to mess this up (ask me how i know)

**Comment by minigamerking** [comment]
> Just to make sure: you ran `/polymer generate-pack` right? I fee like thats the easiest way to mess this up (ask me how i know)

I used `/polymer generate-pack` and the name is there and so is the tooltip, yet the texture doesn't update, I went through the resource pack and the texture is there and i can give myself a regular diamond sword with the custom model data of the life steal sword and the texture looks like the life steal sword.
