### ISSUE TITLE
Allow iterating over Polymer registry entries

### ISSUE THREAD

**Issue by haykam821** [Patbox/polymer#13]
Some way of iterating over both identifiers and content in a Polymer registry would be beneficial, like the vanilla `Registry#getEntries` method.

**Comment by Patbox** [comment]
You can already do that, as it already implements Iterable interface, but on server there is only ItemGroup registry really. On client there are ones for Blocks/Items representations synced with clients

**Comment by haykam821** [comment]
As far as I can see, you can iterate over identifiers or content but not both at the same time.

**Comment by Patbox** [comment]
Ah then yeah
