### ISSUE TITLE
Resource pack couldnt be applied

### ISSUE THREAD

**Issue by Ender-Xvi** [Patbox/polymer#139]
Im using a test server to play around with polymer and filament
but i keep running into a problem when i try to connect to the server i get "disconnection lost Server Resource pack couldnt be applied" 
im sure im missing something but i can't figure it out 

im am using Minecraft version 1.20.1

**Comment by Patbox** [comment]
Check client logs for more info, I imagine autohost isn't configured correctly

**Comment by Ender-Xvi** [comment]
Here is the client log and the Auto-host.  
im sure i messed something up with it 
But reading over things. i cant figure out what i messed up or missed.
 
[latest.log](https://github.com/user-attachments/files/16322344/latest.log)
![image](https://github.com/user-attachments/assets/2ffc9e03-0dd3-4659-8cc5-a550adfa8c60)

Thank you for the help.

**Comment by Merith-TK** [comment]
Typically for basic test server you don't need to have anything in "settings" as autohost by default piggybacks off the Minecraft port for http traffic

**Comment by Ender-Xvi** [comment]
do i just delete whats in the " " for settings?

**Comment by Merith-TK** [comment]
just empty "external_address"

**Comment by Ender-Xvi** [comment]
[latest.log](https://github.com/user-attachments/files/16322458/latest.log)
Still doing it

**Comment by Patbox** [comment]
You need to change external_address to your servers domain/ip, with port being set to some free port
