### ISSUE TITLE
Mod incompatability with Immersive Portals

### ISSUE THREAD

**Issue by ShaKabosh** [Patbox/polymer#14]
I was using the mod Interdimensional on a 1.18.1 Fabric 0.12.12 server, and Immersive Portals 1.1.8 with Polymer 0.2.0-beta.9+1.18.1 via interdimensional
The error was this: https://pastebin.com/QuDz5jm2

**Comment by Patbox** [comment]
Install latest version of polymer. You can get link frow readme

**Comment by ShaKabosh** [comment]
The issue is that the polymer library is embedded in the Interdimensional mod. I have also created an issue on their repository though.

**Comment by Patbox** [comment]
You can still download it and drop into mods folder

**Comment by ShaKabosh** [comment]
Ok, that has worked. Thanks!
