### ISSUE TITLE
1.21+ Polymer is incompatible with Sinytra Connector

### ISSUE THREAD

**Issue by TalonFloof** [Patbox/polymer#150]
When attempting to use Sinytra Connector to load Polymer, [a crash occurs (full logs linked here)](https://github.com/user-attachments/files/16641839/latest.txt) when attempting to apply a mixin within the `polymer-virtual-entity` jar. Attached below is the logs of everything from startup to the crash report.

Mod List
- Polymer 0.9.10+1.21.1
- Sinytra Connector 2.0.0-beta.1+1.21-full
- Forgified Fabric API 0.102.0+2.0.12+1.21.1

**Comment by Patbox** [comment]
That's connector issue, not polymer issue. Polymer library set is targeting Fabric ecosystem (with some quilt support that's practically free). (Neo)Forge isn't officially supported and there is no version for these platforms.
