### ISSUE TITLE
[Feature Request] Add the ability to use polymer on top of an existing server resource pack

### ISSUE THREAD

**Issue by CCF100** [Patbox/polymer#153]
Hi, I was wondering if it was possible to specify a resource pack to inject additional polymer resources into...

**Comment by Patbox** [comment]
You can do it, see https://polymer.pb4.eu/latest/user/resource-pack-custom-assets/

**Comment by CCF100** [comment]
> You can do it, see https://polymer.pb4.eu/latest/user/resource-pack-custom-assets/

I'm sorry I missed that, my bad 😅
