### ISSUE TITLE
Received a registry entry that is unknown to this client

### ISSUE THREAD

**Issue by themg95** [Patbox/polymer#155]
I followed polymer's docs and it said to use the regular fabric way to register items. I did and now I get this error.

**Comment by Patbox** [comment]
Check logs, it should tell you more. It sounds like you missed some registered entry

**Comment by themg95** [comment]
I'm assuming serverside logs? I don't see any errors there

**Comment by themg95** [comment]
Ok, it turns out that I copy-pasted something without checking and it was nothing more than a typo, sorry for wasting your time.
