### ISSUE TITLE
NullPointerException when calling `PalettedContainer.Data.writePacket` without context

### ISSUE THREAD

**Issue by senseiwells** [Patbox/polymer#168]
This issue is regarding a compatibility issue with [ServerReplay](https://github.com/senseiwells/ServerReplay).

With ServerReplay it's possible to write packets without a player context (i.e. ChunkRecordings).

Here is a stacktrace relevant to this issue: https://mclo.gs/lNA4M4I

https://github.com/Patbox/polymer/blob/7388ba96ff3b86b6e0eda6771bba8a116a7b711e/polymer-core/src/main/java/eu/pb4/polymer/core/mixin/block/packet/PalettedContainerDataMixin.java#L31-L37

In this snippet the result of `PacketContext.get()` is a reference to the `MutableContext` thread local instance, which by default returns `ContextProvidingPacketListener.EMPTY` on the `getPacketListener()` call, not `null`, `getPacketListener()` is not marked `@Nullable` so this check is redundant. This results in `PolymerServerNetworking.getMetadata` throwing a `NullPointerException` since there's no actual connection context.

I believe this should be replaced with a `getBackingPacketListener()` call instead.

Even in the case where there is no context should polymer still not replace the block states, just without the player?

**Comment by Patbox** [comment]
Due to it happening in packet, it should convert it  but lack of context will change how other mods will handle it
