### ISSUE TITLE
Alt Armor Handler breaks with Iris

### ISSUE THREAD

**Issue by Justsnoopy30** [Patbox/polymer#18]
The PNG files you reference don't appear to actually exist... this causes anything wearing leather armor to have a missing texture.

Sodium + Polymer:
![image](https://user-images.githubusercontent.com/33374736/156949022-a0e808eb-b7fa-4720-969b-ad57f66af787.png)
Iris + Sodium + Polymer:
![image](https://user-images.githubusercontent.com/33374736/156949046-92cbd32c-add7-411c-9c5e-1c2c58ed9089.png)

Log: https://paste.gg/p/anonymous/b0e4b1938d164d319bb0967346732b9d

**Comment by Patbox** [comment]
Fixed in 0.2.0-beta.29
