### ISSUE TITLE
Geyser support?

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [Patbox/polymer#22]
Heya, I'm planning on using Polymer on my server but i need to ensure that it'd work with Geyser, since this server is mainly geared towards bedrock players

**Comment by halotroop2288** [comment]
It sounds like you haven't tried it yet. If it's not explicitly stated in the README or documentation, it's probably untested.
[Try it and see](https://tryitands.ee/)

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Alright then, thanks!

**Comment by Patbox** [comment]
Mods using polymer *should* generally work. Through you need to apply this workaround setting in geyser. https://github.com/GeyserMC/Geyser/issues/2776

Also if mod requires server resource packs or uses some packet tricks/hacks, it might not fully work so keep that in mind

**Comment by halotroop2288** [comment]
Good to know. I was considering Geyser support as well.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Thanks aha, I'll close the issue now!

**Comment by GamingInfinite** [comment]
I'd like to make a note that I just had a thing where having polymer itself in the server made it where it locked up players, whether that option in Geyser is on or not.

**Comment by GamingInfinite** [comment]
However removing it *seems* to still have everything working just no textures, which I'm pretty sure wouldn't work on Bedrock anyhow.

**Comment by Patbox** [comment]
See this workaround. https://github.com/GeyserMC/Geyser/issues/2776
It's issue with geyser not working corerctly
