### ISSUE TITLE
Incompatibility with recent REI

### ISSUE THREAD

**Issue by ZekeZDev** [Patbox/polymer#35]
With the latest versions of roughly enough items upon world creation the client will crash, This happens with all mods I have tried that rely on Polymer: GOML, Styled chat, Universal graves etc. I am not sure of the exact cause of the error however it seems to be related to Polymer.

Log with universal graves, GOML and roughly enough items + depends:
https://mclo.gs/DMxXoA2

**Comment by Patbox** [comment]
Update Polymer to latest version by hand. You can download it from here https://github.com/Patbox/polymer#download
