### ISSUE TITLE
[Help] What do I put after FabricItemSettings?

### ISSUE THREAD

**Issue by LuciusofLegend** [Patbox/polymer#38]
Alright, I'm jumpin in.  Here is my code for creating a new item (copypasted from the Fabric wiki lol):

public class ModItems implements ModInitializer {
    
    public static final SimplePolymerItem EXPLOSIVE_RUNE = new SimplePolymerItem(new FabricItemSettings().group(ItemGroup.MISC));

    @Override
    public void onInitialize() {
        Registry.register(Registry.ITEM, new Identifier("tutorial", "custom_item"), EXPLOSIVE_RUNE);
    }
}

> 'SimplePolymerItem(net.minecraft.item.Item.Settings, net.minecraft.item.Item)' in 'eu.pb4.polymer.api.item.SimplePolymerItem' 
cannot be applied to '(net.fabricmc.fabric.api.item.v1.FabricItemSettings)'

Ok, so I think I figured this out.  There has to be something after FabricItemSettings, but I don't know what.  I tried a few things but none of them seemed to fix the issue.

At this point I just need help with what that extra bit could be.  Let me know if you need more info, and thanks in advance!

**Comment by Patbox** [comment]
You need to put some vanilla item there. You just pass them as statics from `Items` class

**Comment by LuciusofLegend** [comment]
Oh, ok.  Thanks alot!
