### ISSUE TITLE
nothing that requires geko lib woks

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [Patbox/polymer#45]
https://www.dropbox.com/sh/ib6c6vmkofl40v7/AABlK5jhqK7Ig8QneJNBgk8Ra?dl=0
these are the mods i used

https://www.dropbox.com/s/ugvotvt0fypakpe/Badlion%20Client%202022.09.27%20-%2015.49.10.01.mp4?dl=0
video

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
also every block is a stone block

**Comment by Patbox** [comment]
This is related to PolyMc, not Polymer

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
ok sorry
