### ISSUE TITLE
Compatability with YungsbetterMineshafts and AdvancedGolems

### ISSUE THREAD

**Issue by valous2** [Patbox/polymer#47]
I noticed that this mod when installed along side any of the Yungs better Mods and the mod advancedgolems-1.19-1.2.0-fabric.jar will cause the server to crash on boot, even on a new world generation. I can install any combination of two of theses mods but as soon as I try the third it a no go.

Minecraft version: 1.19.2
Mod Loader: Quilt 0.17.6
[log file](https://gist.github.com/valous2/b21c4abc1a20fb004a3daeb2464a709c)

List and links to installed mods and dependencies.
[Yungs Better Mineshafts](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric/download/4031205)*
[Yungs Api](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/download/4035003)
[Cloth Api](https://www.curseforge.com/minecraft/mc-mods/cloth-config/download/3972420)
[Polymer](https://cdn.modrinth.com/data/xGdtZczs/versions/uZEwXh4D/polymer-all-0.2.18%2B1.19.2.jar)
[Quilt Fabric Api](https://cdn.modrinth.com/data/qvIfYCYJ/versions/zzHaJbi0/quilted-fabric-api-4.0.0-beta.19%2B0.64.0-1.19.2.jar)
[Advanced Golems](https://www.curseforge.com/minecraft/mc-mods/advanced-golems-fabric/download/4048644)
[Tenshi Lib](https://www.curseforge.com/minecraft/mc-mods/tenshilib-fabric/download/4033317)

*I have all of Yungs better mods installed but only takes one of them to produce an error.

I don't know which mod is causing this error so I am submitting this report to all three authors in hopes a fix can be made.

**Comment by Patbox** [comment]
Does it happen when you install other polymer mods instead of Advanced Golems? ([Illager Expansion Polymer Port](https://modrinth.com/mod/illager-expansion-polymer) should be best one to test)

**Comment by valous2** [comment]
Havn't tried any polymer mods but I'll give give this one a try and let you know.

**Comment by valous2** [comment]
Ok tried a fresh install using same mods except replaced Advanced Golems / Tenshi Lib with the Illager Expansion Port and still get  a crash but the log looks way different. Does Illager Expansion have any prerequisite mods or libs i missed?
[updated log](https://gist.github.com/valous2/825e79ba7cc6870154807200abb29f17)

**Comment by Patbox** [comment]
Ah right, it requires https://modrinth.com/mod/trinkets-polymer

**Comment by valous2** [comment]
Ok once I added the trinkets mod the pillager mod now loads with the other two without crashing. I even further tested by loading all of Yungs other mods and it loaded fine.

**Comment by Patbox** [comment]
Yeah then it is issue with Advanced Golems mod loading some class too early, not Polymer (or YBM probably)

**Comment by valous2** [comment]
Ok thank you for taking the time to look into this. have a great evening / morning.
