### ISSUE TITLE
Incompatibility with memoryleakfix

### ISSUE THREAD

**Issue by LostLuma** [Patbox/polymer#51]
Using polymer `0.3.0-rc.2+1.19.3-rc3` and memoryleakfix `1.19.3-0.7.0` causes the game to show an error screen upon joining a singleplayer world, however no error information is found in the Minecraft log.

Screenshot: https://files.lostluma.dev/W1q49D.png
Minecraft Log: https://files.lostluma.dev/NhZCDP.txt
 
Previously using the 1.19.2 versions of these mods worked fine.

**Comment by Patbox** [comment]
Fixed in 0.3.0-rc.4
