### ISSUE TITLE
[Compat] Ghost Blocks with Drink Beer Mod - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [Patbox/polymer#53]
https://github.com/ClockwerkKaiser/DrinkBeer/issues/5

**Comment by Patbox** [comment]
Does it happen on server or on singleplayer?

**Comment by Patbox** [comment]
Also doesnthe block still show correctly on f3?

**Comment by xR4YM0ND** [comment]
multiplayer & singleplayer 

F3 Targeted Block -> Same info on normal mug & ghost mug

**Comment by Patbox** [comment]
Is it only rendering issue?

**Comment by xR4YM0ND** [comment]
idk the block stays there ( as ghost block ) , but when i hover over the ghost block the F3 shows me the targeted block ( ghost block )

**Comment by xR4YM0ND** [comment]
You could test it for yourself, you only need Fabric 1.19.2 , Drink Beer Unofficial & Polymer ( Fabric Loader 0.14.11 )

**Comment by Patbox** [comment]
Can't recreate that

**Comment by Patbox** [comment]
Ah wait, got it after checking the report

**Comment by Patbox** [comment]
Should be fixed in 0.2.22+1.19.2! 0.3.0+1.19.3 version wasn't effected
