### ISSUE TITLE
Crossbows with custom Polymer-enabled enchantments have visual glitch with loading

### ISSUE THREAD

**Issue by firenh** [Patbox/polymer#54]
When crossbows are loaded with a custom enchantment enabled with Polymer, they don't show the loaded state visually to the player. Instead, they just look unloaded, but when used again, shoot the arrow inside. 

How to recreate:

1) Create any custom enchantment with Polymer
2) Put enchantment on Crossbow and try to use

**Comment by Patbox** [comment]
I imagine it effects both 1.19.2 and 1.19.3?

**Comment by Patbox** [comment]
Should be fixed on latest (1.19.2 and 1.19.3)
