### ISSUE TITLE
REI compatibility doesn't work on 1.19.3 (REI v10.0.581)

### ISSUE THREAD

**Issue by JLargent42** [Patbox/polymer#55]
REI does not recognize custom items or blocks in a server-side Polymer mod. EMI does work, though.

**Comment by Patbox** [comment]
Any logs?

**Comment by JLargent42** [comment]
Sure. 
[Client](https://pastebin.com/Y6U7WPK0)
[Server](https://pastebin.com/bwNadmWx)
[REI](https://pastebin.com/mPeBEGDK)
