### ISSUE TITLE
player frozen on polymer 0.2.0-rc.4.6+1.18.2

### ISSUE THREAD

**Issue by Monster-Zer0** [Patbox/polymer#57]
when playing skylore beta 2.2 https://www.curseforge.com/minecraft/modpacks/aof-presents-skylore/files/4356684 along with polymer and universal graves. when a player dies they will be unable to move.

sometimes breaking their grave after the fact will do a client crash.

**Comment by Patbox** [comment]
We tried to reproduce it, but without success... keeping it as plausible, but not fully confirmed

**Comment by Patbox** [comment]
As there were no instances reported (either here or directly to me). I'm closing this one
