### ISSUE TITLE
[Bug] Crash on Startup

### ISSUE THREAD

**Issue by TheAyes** [Patbox/polymer#58]
Everything works fine without polymere. Adding it causes a crash even before the Minecraft Window pops up.
Logs:
https://mclo.gs/PN11LR3

No Mods except Polymer

**Comment by LostLuma** [comment]
You're running an outdated version of the loader beta, this issue no longer appears on `0.18.1-beta.65`.

**Comment by Patbox** [comment]
Issue with quilt beta loader version, not polymers

**Comment by TheAyes** [comment]
Well... It appears they've just rolled out an update that fixed the issue a few minutes ago.
