### ISSUE TITLE
"Numismatic Overhaul" doesn't handle Polymer/Empty Stacks on client

### ISSUE THREAD

**Issue by c1oudychan** [Patbox/polymer#59]
When Polymer items are on sale, chunks are not loaded.

1. Install any modification with Polymer
2. Load a Polymer item into the store
3. Another player comes and his chunks are not loaded
4. When you clean the store and the Player re-enters chunks loading

Screenshot from player on my server.

![image](https://user-images.githubusercontent.com/96329203/215972555-07c7788f-4b7a-41d7-9d7a-dbb366cb6492.png)

**Comment by Patbox** [comment]
Any logs?

**Comment by c1oudychan** [comment]
no errors in the console. just not loading

https://pastes.dev/FEUFBEvbJ2

**Comment by Patbox** [comment]
On client?

**Comment by c1oudychan** [comment]
oh yes, forgot about a client

https://pastes.dev/dhdCeQtsQP

**Comment by Patbox** [comment]
Looks more of like issue with Numismatic Overhaul not handling tradea with empty stacks correctly. report this to them too

**Comment by Patbox** [comment]
Installing polymer on client might help with this issue, but I can't fully confirm that

**Comment by Patbox** [comment]
After some tinkering, this might be fixed on 0.5.8+1.20.1
