### ISSUE TITLE
Recipe Support (RecipeSerializer, RecipeType) is broken in /dev

### ISSUE THREAD

**Issue by aws404** [Patbox/polymer#6]
In the /dev branches, uppon joing a server with custom RecipeSerializers/Types registered, the client disconnects. I believe the cause is that the SynchronizeRecipesS2CPacketMixin has been annotated with `@Environment(EnvType.CLIENT)` and moved into the `client` section of `polymer.mixins.json`.

**Comment by Patbox** [comment]
Oops, going to fix that now

**Comment by Patbox** [comment]
Should be fixed in beta.2
