### ISSUE TITLE
feature request: if mod exists on client, dont do polymer things

### ISSUE THREAD

**Issue by Merith-TK** [Patbox/polymer#68]
This idea came from how CC:R-Polymer works, the idea is that vanilla players will see the polymer port version of the blocks, but if the client has the CC:R mod, it could show that player the standard CC:R items and interactions, 

This feature would allow for "hybrid" server/client mods to exist, where they exist serverside, the client wouldn't need the mod, but the client would be enhanced if they have the mod it is better!

**Comment by Patbox** [comment]
This can be done already, but requires mods to implement logic themselves
