### ISSUE TITLE
Description unlcear, mod converter or no?

### ISSUE THREAD

**Issue by allanonmage** [Patbox/polymer#74]
1. Intro
`It's a library for creating server side content, that work for player's without mods or (required) resource packs! You can create blocks, items and entities, that not only will work fully server side (and singleplayer), but also are still real custom ones, allowing for better integration with data packs and other mods (servers still see it as mymod:custom and not minecraft:player_head, unlike bukkit/spigot ones, that only emulate them).`

2. Description
`Any mod using this library shouldn't be required on the client side! However, as stated above, there are few small quality of life things added with it. So you might want to recommend it or include with your mod pack.`

3. Caveat
`This mod doesn't convert existing mods to server side ones. While it's possible to do so with manual coding, for that you might want to use PolyMc as long as you don't need to use regular mods on the client (for example with a modpack).`

1 and 2 are congruent with each other, but 3 is not.  If 3 is correct, then what does this mod do?  Is it a backend/prerequisite library (sometimes referred to as "a dependency") made for mod developers to develop to/change their mod, such that their final product won't require a mod client-side?

I am a dev and an admin, so please, talk nerdy to me.

**Comment by Patbox** [comment]
Yeah, it's a library/dependency other mods can use to create server side content. By itself if doesn't change any existing/modded stuff. Additionally everything needs to be specified by developer, nothing is fully automatic

**Comment by allanonmage** [comment]
OK, that makes sense then.
