### ISSUE TITLE
Add some features for ElementHolder

### ISSUE THREAD

**Issue by ghost** [Patbox/polymer#77]
- `ElementHolder` can inherit `onTick` to do something when it ticks. Instead, I suggest adding a callbacks on tick to `ElementHolder` or `VirtualElement`. This is useful when writing in the Builder or DSL style.
- When `ElementHolder`'s `VirtualElement`s are riding on Entity, `notifyElementsOfPositionUpdate` is called every tick, so trembling occurs. So I suggest adding a property to determine whether to call `notifyElementsOfPositionUpdate` or not.
- To check if a particular `ElementHolder` is attached to a target, create and use a class that inherits `ElementHolder`, call the `ElementHolder`s using impl, and then check if an instance of that class is included. So, I suggest to make sure `ElementHolder` can be identified by `String` or `Identifier`, and api can check if a specific `ElementHolder` is already attached to the target.

**Comment by Patbox** [comment]
Added way to disable sending of positions to client. Not sure if I want to go with other two
