### ISSUE TITLE
Wrong super call in TestEntity2

### ISSUE THREAD

**Issue by Dev0Louis** [Patbox/polymer#78]
In https://github.com/Patbox/polymer/blob/dev/1.20/polymer-core/src/testmod/java/eu/pb4/polymertest/TestEntity2.java there is

```Java
    @Override
    public void onStoppedTrackingBy(ServerPlayerEntity player) {
        player.networkHandler.sendPacket(new PlayerRemoveS2CPacket(List.of(this.getUuid())));
        super.onStartedTrackingBy(player);
    }
```

It calls super.onStartedTrackingBy, but I think it should be super.onStoppedTrackingBy

**Comment by Patbox** [comment]
This is more of polymer test mode than anything so doesn't matter
