### ISSUE TITLE
Through Velocity: Received chat packet with missing or invalid signature

### ISSUE THREAD

**Issue by ericthelemur** [Patbox/polymer#88]
Running a Fabric 1.20.1 server with Fabric API, FabricProxy-Lite and Polymer through a basic Velocity server gives the `Received chat packet with missing or invalid signature` error. Removing Polymer resolves this, and this occurs both on Windows and Linux.

Settings are all default, besides the required to connect Velocity to Fabric. I've uploaded a zip of each to https://owen.sites.uwcs.co.uk/files/server.zip and https://owen.sites.uwcs.co.uk/files/vel.zip though I'd understand if you don't trust these.

**Comment by Patbox** [comment]
Thats weird, as I am running server using polymer wirh velociry without this issue. Make sure you run latest versions of both

**Comment by ericthelemur** [comment]
Everything is no more than a week old, though I'll give it a go with a fresh copy of everything tomorrow. Only thing I know not latest is Minecraft being 1.20.1. not 1.20.2 since other mods aren't updated yet.

**Comment by Patbox** [comment]
This is likely issue with velocity itself, not caused by polymer!
