### ISSUE TITLE
[1.20.1] Server flood more error

### ISSUE THREAD

**Issue by DonorKrovi** [Patbox/polymer#91]
https://mclo.gs/svJiiWk

I'm use Connector-1.0.0-beta.21+1.20.1+dev-gb0e0d44-full.jar
As soon as the server is fully up and running, it floods into the console

**Comment by DonorKrovi** [comment]
Also, the server started, but the connection or its ping in the server list is not possible
![image](https://github.com/Patbox/polymer/assets/60231586/8ce9e7db-ac25-425b-8b92-a6e40776f8ca)

**Comment by Patbox** [comment]
This is caused by bad mixin from `connectivity` mod. Report it to them
